/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AutenticacaoRouteRouteImport } from './routes/autenticacao.route'
import { Route as IndexRouteRouteImport } from './routes/index.route'

const AutenticacaoRouteRoute = AutenticacaoRouteRouteImport.update({
  id: '/autenticacao',
  path: '/autenticacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/autenticacao': typeof AutenticacaoRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/autenticacao': typeof AutenticacaoRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/autenticacao': typeof AutenticacaoRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autenticacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autenticacao'
  id: '__root__' | '/' | '/autenticacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AutenticacaoRouteRoute: typeof AutenticacaoRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/autenticacao': {
      id: '/autenticacao'
      path: '/autenticacao'
      fullPath: '/autenticacao'
      preLoaderRoute: typeof AutenticacaoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AutenticacaoRouteRoute: AutenticacaoRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
